### ISSUE TITLE
Bulk photos restore

### ISSUE THREAD

**Issue by neoblizz** [Nutlope/restorePhotos#11]
Is there a way I can use this tool to restore photos in bulk? Either online or locally?

**Comment by Nick-h4ck3r** [comment]
I think, we can do something like taking all photos from user, storing them on cloud, and getting link for each. And, passing the links to bakend one-by-one, and keeping the results in storage, and displaying all at once to user.

Till all this happens, user will be shown a progress bar, accroding to the work done.  

Please, if you could give me some direction or resources to how to exactly do this, I would like to take on this issue.

**Comment by Nutlope** [comment]
I don't want folks to use this for bulk photo restore (and you currently can't since I'm rate limiting the API). If you'd like to do this, clone the project, use your own replicate API key, and write a script that feeds your photos to your endpoint and saves the URLs back.

**Comment by Nick-h4ck3r** [comment]
Makes sense.

**Comment by neoblizz** [comment]
> I don't want folks to use this for bulk photo restore (and you currently can't since I'm rate limiting the API) since it costs me $ per invocation. The intention is for people to use this for a few of their personal photos.
> 
> If you'd like to do bulk photo restore, clone the project, use your own replicate API key, and write a script that feeds your photos to your endpoint and saves the URLs back.

That is fine, which is why I was wondering if there was a way to go about it locally. And it seems like it will be through your own API key and a script. Do you have a pointer to where that skip would target the input?
