### ISSUE TITLE
An issue when uploading another photo, just after processing another photo

### ISSUE THREAD

**Issue by Ndivho69** [Nutlope/restorePhotos#17]
First of all i'd like to say, damm this is great, i encountered an error on my second upload just after processing the first photo, My photo could get uploaded ,but never displayed the second photo , to fix this i had to re-route to main page and back to the upload button again... please fix this... great stuff guys

**Comment by Nutlope** [comment]
Let me know if this happened to you more than one time, assuming it was hopefully just a fluke.

**Comment by Ndivho69** [comment]
The issue has been succesfully resolved, thank you ,Great project man
