### ISSUE TITLE
Add support for disallowing people from NSFW pictures with the help of NSFWJS 

### ISSUE THREAD

**Issue by shivaylamba** [Nutlope/restorePhotos#2]
We can use https://nsfwjs.com/ to enable check for NSFW uploads while uploading any image on the application

**Comment by Nutlope** [comment]
Good idea, want to submit a PR @shivaylamba?

**Comment by shivaylamba** [comment]
Yeah sure @Nutlope I will look to implement it

**Comment by shivaylamba** [comment]
HI, @Nutlope before creating the Pull Request, I wanted to get a confirmation, if this implementation looks good: 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/19529592/212192218-de3697ec-efc1-4eb4-9afa-079725aee60c.png">

I am using the Tailwind Alerts (https://v1.tailwindcss.com/components/alerts) to show an alert, If the user uploads an NSFW image. Let me know if this implementation looks good.

**Comment by Nutlope** [comment]
@shivaylamba Looks good to me! Let's make it say something like "Detected a NSFW image" please

**Comment by SubhamSubhasisPatra** [comment]
@shivaylamba Why don't you try something `NSFW image Content are against the community guideline , Please try to avoid` or else `NSFW image are not allowed`.

**Comment by Nutlope** [comment]
Done #24
