### ISSUE TITLE
Hard-coded download file path

### ISSUE THREAD

**Issue by mvalipour** [Nutlope/restorePhotos#4]
On my phone it keeps asking me to replace the current downloaded file, because this file name here is hard-coded:

https://github.com/Nutlope/restorePhotos/blob/7baa5f6791b304a9ebf84eb5998b8de44a3b4add/pages/restore.tsx#L163-L166

I suggest getting the file name from `originalPhoto` and using that here instead.

**Comment by Nutlope** [comment]
Great suggestion, implemented! https://github.com/Nutlope/restorePhotos/commit/3a639da730c60c3884bd15ed25417f8beec37a64
