### ISSUE TITLE
Blurred faces

### ISSUE THREAD

**Issue by has9800** [Nutlope/restorePhotos#5]
Faces in the images have a black blur over them instead of clearing old images up. Tried different image types and sizes in kB. This happens to all images I tried, approx 6 different images all have the same issue. See attached example below. 

![image](https://user-images.githubusercontent.com/100562717/211445294-60cc93e0-9aee-48c2-af15-73c1c3930618.jpeg)

**Comment by Nutlope** [comment]
Unfortunately can't make tweaks to the machine learning model since I'm using an API with a pre-trained model.
