### ISSUE TITLE
Can you share the license for this app?

### ISSUE THREAD

**Issue by Bam92** [Nutlope/restorePhotos#7]

**Comment by Nutlope** [comment]
No license. You're free to take the code and do whatever you'd like with it!

**Comment by llegomark** [comment]
> No license. You're free to take the code and do whatever you'd like with it!

Great, thank you for sharing, Sir Nutlope. I will definitely fork the repository and build a web app with it.

**Comment by mvalipour** [comment]
Just a note that "no license" doesn't imply "use it freely" — in fact no license has more limitations than some other open-source licenses.

Pick something from here: https://choosealicense.com/
