### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by yllekz** [Nutlope/restorePhotos#8]
Hey there, this is a pretty cool resource. Any chance it could be packaged into a Docker image so it could be deployed in that manner?

**Comment by Nutlope** [comment]
Hey @yllekz! Where are you looking to deploy it out of curiosity? Would the one click button to Vercel not work for your use case?

**Comment by yllekz** [comment]
I have a server at home running Docker and just wanted to add it to my armada of services. I'd prefer not to run it as a native app but just as another container. Just curious.

**Comment by Nutlope** [comment]
Ah, nice! I have no plans to package into a Docker image but you can follow the docs here and do it yourself: https://nextjs.org/docs/deployment#docker-image
